### ISSUE TITLE
A program of Depth First Search

### ISSUE THREAD

**Issue by jatinagg2** [jatinagg2/DAA-Programs#1]
Program of DFS Algorithm is required in any language (Preferred Java, Python and C++). The code should be proper without any extra spaces in between. The file name should be in CamelCase form and it must lie in appropriate repository.

**Comment by ajyan** [comment]
Hi, can I be assigned this issue?

**Comment by ajyan** [comment]
@jatinagg2

**Comment by gayathri0329** [comment]
Hey, I would like to give this a try, could you assign this to me? @jatinagg2

**Comment by atingarg1406** [comment]
I would like to do this task. Do assign me for that @jatinagg2

**Comment by jatinagg2** [comment]
> Hey, I would like to give this a try, could you assign this to me? @jatinagg2

You can proceed @gayathri0329 
Try to code your program in Python or Java and with proper format as mentioned in the description.

**Comment by cardboardboxpepe** [comment]
Can you assign me this issue? I can do it in whatever language that isn't taken
