### ISSUE TITLE
Check redundant brackets program

### ISSUE THREAD

**Issue by jatinagg2** [jatinagg2/DAA-Programs#10]
Code the given problem using any of the programming language.

Statement:
For a given expression in the form of a string, find if there exist any redundant brackets or not. It is given that the expression contains only rounded brackets or parenthesis and the input expression will always be balanced.
A pair of the bracket is said to be redundant when a sub-expression is surrounded by unnecessary or needless brackets.

Example:
Expression: (a+b)+c
Since there are no needless brackets, hence, the output must be 'false'.

Expression: ((a+b))
The expression can be reduced to (a+b). Hence the expression has redundant brackets and the output will be 'true'.

Input Format:
The first and the only line of input contains a string expression, without any spaces in between.

Output Format:
The first and the only line of output will print either 'true' or 'false'(without the quotes) denoting whether the input expression contains redundant brackets or not.

Constraints:
0 <= N <= 10^6
Where N is the length of the expression.
Time Limit: 1 second

Sample Input 1:
a+(b)+c

Sample Output 1:
true

**Comment by ShivangiRai1310** [comment]
Can I work on this issue using C++?

**Comment by atingarg1406** [comment]
I can solve the given problem in Python. Please assign it to me.

**Comment by jatinagg2** [comment]
Go ahead @ShivangiRai1310 @atingarg1406

**Comment by SLAYEEERRR** [comment]
public static boolean checkRedundantBrackets(String expression) {
		// Your code goes here
		Stack<Character> input = new Stack<Character>();

		int len = expression.length();
		int i = 0;

		for (int k = 0; k < len; k++) {
			int count = 0;
			if (expression.charAt(k) == ')') {
				while (input.peek() != '(') {
					input.pop();
					if (input.peek() == '+' || input.peek() == '-' || input.peek() == '*' || input.peek() == '/') {
						count++;
					}

				}
				if (count == 0) {
					return true;
				}
				input.pop();
			} else {
				input.push(expression.charAt(k));

			}
		}
		return false;
	}
