### ISSUE TITLE
Prim's Algorithm Program

### ISSUE THREAD

**Issue by jatinagg2** [jatinagg2/DAA-Programs#2]
A program of Prim's Algorithm is required in any language. The code should be in proper way without any extra spaces in between and must lie in appropriate repository.

**Comment by atingarg1406** [comment]
I want to do this task. Do assign it to me @jatinagg2

**Comment by jatinagg2** [comment]
> I want to do this task. Do assign it to me @jatinagg2

You can do @atingarg1406
