### ISSUE TITLE
Array Intersection Program

### ISSUE THREAD

**Issue by jatinagg2** [jatinagg2/DAA-Programs#9]
Code the given problem in Python. Have to consider the time and space complexity.

Statement:
You have been given two integer arrays/list(ARR1 and ARR2) of size N and M, respectively. You need to print their intersection; An intersection for this problem can be defined when both the arrays/lists contain a particular value or to put it in other words, when there is a common value that exists in both the arrays/lists.

Input format:
The first line contains an Integer 't' which denotes the number of test cases or queries to be run. Then the test cases follow.
The first line of each test case or query contains an integer 'N' representing the size of the first array/list.
The second line contains 'N' single space separated integers representing the elements of the first the array/list.
The third line contains an integer 'M' representing the size of the second array/list.
The fourth line contains 'M' single space separated integers representing the elements of the second array/list.

Output format:
For each test case, print the intersection elements in a row, separated by a single space.
Output for every test case will be printed in a separate line.

Constraints:
1 <= t <= 10^2
0 <= N <= 10^6
0 <= M <= 10^6
Time Limit: 1 sec

Sample Input:
2
6
2 6 8 5 4 3
4
2 3 4 7 
2
10 10
1
10

Sample Output:
2 3 4
10

**Comment by atingarg1406** [comment]
I want to solve the given problem. Please assign it to me @jatinagg2
